### ISSUE TITLE
Algorithm Deep Dive: XD

### ISSUE THREAD

**Issue by ktmeaton** [phac-nml/rebar#16]
I want to write documentation about how the algorithm works (ex. [run.md](https://github.com/phac-nml/rebar/blob/main/docs/run.md)) with a case study. SARS-CoV-2 recombinant `XD` often confuses me, so I'll work through some of the results here.

**Comment by ktmeaton** [comment]
`rebar dataset download --name sars-cov-2 --tag 2023-12-06 --output-dir dataset/sars-cov-2/2023-12-06`

- Commit: c80a888e8

**Comment by ktmeaton** [comment]
## Designated Recombinant

What is the evidence for `BA.1.15` as a secondary parent?

```bash
rebar run \
  --dataset-dir dataset/sars-cov-2/2023-12-06 \
  --output-dir output/sars-cov-2/2023-12-06/XD \
  --verbosity debug \
  --populations "XD" \
  --parents "B.1.617.2,BA.1.15"
```

- Hypothesis: `NonRecursiveRecombinant: score=20, conflict=18`
- Regions: regions_intersect: {"210":{"start":210,"end":21762,"origin":"B.1.617.2"},"22578":{"start":22578,"end":25469,"origin":"BA.1.15"},"25584":{"start":25584,"end":29402,"origin":"B.1.617.2"}}

```yaml
score:
  - B.1.617.2: -8
  - BA.1.15: 28

support:
  - B.1.617.2 (10): G210T, G15451A, C16466T, C21618G, T26767C, T27638C, C27752T, A28461G, G28881T, G29402T
  - BA.1.15 (28): G22578A, T22673C, C22674T, T22679C, C22686T, G22813T, T22882G, G22898A, G22992A, C22995A, A23013C, A23040G, G23048A, A23055G, A23063T, T23075C, C23202A, A23403G, C23525T, T23599G, C23604A, C23854A, G23948T, C24130A, A24424T, T24469A, C24503T, C25000T

conflict_ref:
  - B.1.617.2 (0):
  - BA.1.15 (0):

conflict_alt:
  - B.1.617.2 (18): A1321C, G4181T, C6402T, C7124T, C7851T, A8723G, C8986T, G9053T, A11201G, A11332G, C14407T, T15264C, C19220T, G21641T, C25667T, G25855T, C27874T, G28916T
  - BA.1.15 (0):

private:
  - B.1.617.2 (18): A1321C, G4181T, C6402T, C7124T, C7851T, A8723G, C8986T, G9053T, A11201G, A11332G, C14407T, T15264C, C19220T, G21641T, C25667T, G25855T, C27874T, G28916T
  - BA.1.15 (0):
```
